### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by alstn113** [pknu-wap/collab-note#8]
# [ FEATURE REQUEST ]

## 작업 리스트

- [ ] 체크 리스트를 작성하세요

**Comment by InSange** [comment]
생각보다 멋지군요?

**Comment by InSange** [comment]
> # [ FEATURE REQUEST ]
> ## 작업 리스트
> * [ ]  체크 리스트를 작성하세요
> 
> ## 참고사항
> ## 예상 소요 시간

별로에요
